### ISSUE TITLE
Battery gives 00 all the time

### ISSUE THREAD

**Issue by joaoasilva** [RoyOltmans/aqualin#1]
Hi,

Thank you so much for your effort in reverse eng. this.
I've tried the timeronoff_battery.sh but I always seem to get 00, all the other ones work perfectly fine.
Am I missing something?

Thanks

**Comment by RoyOltmans** [comment]
Ah thats funny, think thats 100% (capping off at 2 chars) ;-)


Met vriendelijke groet,
Kind regards,

Roy Oltmans

**Comment by RoyOltmans** [comment]
Its btw the response of the valve itself, it's the readout info (I have not altered any data)...

Met vriendelijke groet,
Kind regards,

Roy Oltmans
